services:
  app1:
    image: matching-engine-image
    container_name: matching-engine
    build:
      context: ./matching-engine
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cex-mysql:3306/mydb
      SPRING_REDIS_HOST: cex-redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: cex-kafka:9092
    ports:
      - "8081:8081"

  app2:
    image: order-service-image
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cex-mysql:3306/mydb
      SPRING_REDIS_HOST: cex-redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: cex-kafka:9092
    ports:
      - "8082:8082"
